[2024-05-26T06:51:40.185+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/data_processing.py
[2024-05-26T06:51:40.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_processing.py for tasks to queue
[2024-05-26T06:51:40.192+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:51:40.191+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing.py
[2024-05-26T06:51:40.210+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:51:40.202+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:51:40.211+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing.py
[2024-05-26T06:51:40.251+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_processing.py took 0.079 seconds
[2024-05-26T06:52:10.454+0000] {processor.py:161} INFO - Started process (PID=437) to work on /opt/airflow/dags/data_processing.py
[2024-05-26T06:52:10.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_processing.py for tasks to queue
[2024-05-26T06:52:10.459+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:52:10.458+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing.py
[2024-05-26T06:52:10.465+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:52:10.463+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:52:10.466+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing.py
[2024-05-26T06:52:10.491+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_processing.py took 0.046 seconds
[2024-05-26T06:52:40.548+0000] {processor.py:161} INFO - Started process (PID=709) to work on /opt/airflow/dags/data_processing.py
[2024-05-26T06:52:40.550+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_processing.py for tasks to queue
[2024-05-26T06:52:40.553+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:52:40.552+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing.py
[2024-05-26T06:52:40.560+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:52:40.558+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:52:40.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing.py
[2024-05-26T06:52:40.592+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_processing.py took 0.054 seconds
[2024-05-26T06:53:11.217+0000] {processor.py:161} INFO - Started process (PID=981) to work on /opt/airflow/dags/data_processing.py
[2024-05-26T06:53:11.223+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_processing.py for tasks to queue
[2024-05-26T06:53:11.236+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:53:11.234+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing.py
[2024-05-26T06:53:11.271+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:53:11.261+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:53:11.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing.py
[2024-05-26T06:53:11.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_processing.py took 0.143 seconds
[2024-05-26T06:53:41.749+0000] {processor.py:161} INFO - Started process (PID=1253) to work on /opt/airflow/dags/data_processing.py
[2024-05-26T06:53:41.750+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_processing.py for tasks to queue
[2024-05-26T06:53:41.753+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:53:41.752+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing.py
[2024-05-26T06:53:41.761+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:53:41.758+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:53:41.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing.py
[2024-05-26T06:53:41.791+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_processing.py took 0.053 seconds
[2024-05-26T06:54:11.994+0000] {processor.py:161} INFO - Started process (PID=1525) to work on /opt/airflow/dags/data_processing.py
[2024-05-26T06:54:11.995+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_processing.py for tasks to queue
[2024-05-26T06:54:11.998+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:54:11.997+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing.py
[2024-05-26T06:54:12.004+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:54:12.002+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:54:12.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing.py
[2024-05-26T06:54:12.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_processing.py took 0.048 seconds
[2024-05-26T06:54:42.093+0000] {processor.py:161} INFO - Started process (PID=1797) to work on /opt/airflow/dags/data_processing.py
[2024-05-26T06:54:42.095+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_processing.py for tasks to queue
[2024-05-26T06:54:42.098+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:54:42.097+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing.py
[2024-05-26T06:54:42.104+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:54:42.102+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:54:42.105+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing.py
[2024-05-26T06:54:42.128+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_processing.py took 0.046 seconds
[2024-05-26T06:55:12.399+0000] {processor.py:161} INFO - Started process (PID=2069) to work on /opt/airflow/dags/data_processing.py
[2024-05-26T06:55:12.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_processing.py for tasks to queue
[2024-05-26T06:55:12.404+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:55:12.403+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing.py
[2024-05-26T06:55:12.410+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:55:12.408+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:55:12.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing.py
[2024-05-26T06:55:12.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_processing.py took 0.046 seconds
[2024-05-26T06:55:42.786+0000] {processor.py:161} INFO - Started process (PID=2341) to work on /opt/airflow/dags/data_processing.py
[2024-05-26T06:55:42.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_processing.py for tasks to queue
[2024-05-26T06:55:42.792+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:55:42.791+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing.py
[2024-05-26T06:55:42.800+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:55:42.798+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:55:42.801+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing.py
[2024-05-26T06:55:42.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_processing.py took 0.059 seconds
