[2024-05-26T06:51:40.197+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/data_collection.py
[2024-05-26T06:51:40.199+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_collection.py for tasks to queue
[2024-05-26T06:51:40.203+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:51:40.203+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_collection.py
[2024-05-26T06:51:40.218+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:51:40.213+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_collection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_collection.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:51:40.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_collection.py
[2024-05-26T06:51:40.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_collection.py took 0.067 seconds
[2024-05-26T06:52:10.461+0000] {processor.py:161} INFO - Started process (PID=440) to work on /opt/airflow/dags/data_collection.py
[2024-05-26T06:52:10.462+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_collection.py for tasks to queue
[2024-05-26T06:52:10.465+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:52:10.465+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_collection.py
[2024-05-26T06:52:10.472+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:52:10.470+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_collection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_collection.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:52:10.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_collection.py
[2024-05-26T06:52:10.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_collection.py took 0.044 seconds
[2024-05-26T06:52:40.560+0000] {processor.py:161} INFO - Started process (PID=712) to work on /opt/airflow/dags/data_collection.py
[2024-05-26T06:52:40.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_collection.py for tasks to queue
[2024-05-26T06:52:40.565+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:52:40.565+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_collection.py
[2024-05-26T06:52:40.575+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:52:40.573+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_collection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_collection.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:52:40.576+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_collection.py
[2024-05-26T06:52:40.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_collection.py took 0.055 seconds
[2024-05-26T06:53:11.249+0000] {processor.py:161} INFO - Started process (PID=984) to work on /opt/airflow/dags/data_collection.py
[2024-05-26T06:53:11.253+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_collection.py for tasks to queue
[2024-05-26T06:53:11.266+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:53:11.264+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_collection.py
[2024-05-26T06:53:11.290+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:53:11.284+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_collection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_collection.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:53:11.292+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_collection.py
[2024-05-26T06:53:11.333+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_collection.py took 0.123 seconds
[2024-05-26T06:53:41.757+0000] {processor.py:161} INFO - Started process (PID=1256) to work on /opt/airflow/dags/data_collection.py
[2024-05-26T06:53:41.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_collection.py for tasks to queue
[2024-05-26T06:53:41.762+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:53:41.761+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_collection.py
[2024-05-26T06:53:41.769+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:53:41.767+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_collection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_collection.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:53:41.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_collection.py
[2024-05-26T06:53:41.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_collection.py took 0.054 seconds
[2024-05-26T06:54:12.004+0000] {processor.py:161} INFO - Started process (PID=1528) to work on /opt/airflow/dags/data_collection.py
[2024-05-26T06:54:12.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_collection.py for tasks to queue
[2024-05-26T06:54:12.008+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:54:12.007+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_collection.py
[2024-05-26T06:54:12.015+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:54:12.013+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_collection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_collection.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:54:12.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_collection.py
[2024-05-26T06:54:12.044+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_collection.py took 0.049 seconds
[2024-05-26T06:54:42.159+0000] {processor.py:161} INFO - Started process (PID=1802) to work on /opt/airflow/dags/data_collection.py
[2024-05-26T06:54:42.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_collection.py for tasks to queue
[2024-05-26T06:54:42.163+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:54:42.163+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_collection.py
[2024-05-26T06:54:42.168+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:54:42.167+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_collection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_collection.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:54:42.169+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_collection.py
[2024-05-26T06:54:42.209+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_collection.py took 0.056 seconds
[2024-05-26T06:55:12.408+0000] {processor.py:161} INFO - Started process (PID=2072) to work on /opt/airflow/dags/data_collection.py
[2024-05-26T06:55:12.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_collection.py for tasks to queue
[2024-05-26T06:55:12.412+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:55:12.411+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_collection.py
[2024-05-26T06:55:12.418+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:55:12.417+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_collection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_collection.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:55:12.419+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_collection.py
[2024-05-26T06:55:12.444+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_collection.py took 0.046 seconds
[2024-05-26T06:55:42.797+0000] {processor.py:161} INFO - Started process (PID=2344) to work on /opt/airflow/dags/data_collection.py
[2024-05-26T06:55:42.798+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_collection.py for tasks to queue
[2024-05-26T06:55:42.801+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:55:42.801+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_collection.py
[2024-05-26T06:55:42.809+0000] {logging_mixin.py:188} INFO - [2024-05-26T06:55:42.807+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_collection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_collection.py", line 5, in <module>
    from api.controllers.data_controller import create_data, get_news
ModuleNotFoundError: No module named 'api'
[2024-05-26T06:55:42.810+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_collection.py
[2024-05-26T06:55:42.837+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_collection.py took 0.053 seconds
